/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellActivityRouteImport } from './routes/_shell.activity'
import { Route as ShellBoardRouteImport } from './routes/_shell.board'
import { Route as ShellCompanyRouteImport } from './routes/_shell.company'
import { Route as ShellGraphRouteImport } from './routes/_shell.graph'
import { Route as ShellReviewRouteImport } from './routes/_shell.review'
import { Route as ShellKnowledgeIndexRouteImport } from './routes/_shell.knowledge.index'
import { Route as ShellKnowledgeIdRouteImport } from './routes/_shell.knowledge.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellActivityRoute = ShellActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBoardRoute = ShellBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCompanyRoute = ShellCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGraphRoute = ShellGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReviewRoute = ShellReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ShellRoute,
} as any)
const ShellKnowledgeIndexRoute = ShellKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellKnowledgeIdRoute = ShellKnowledgeIdRouteImport.update({
  id: '/knowledge/$id',
  path: '/knowledge/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof ShellActivityRoute
  '/board': typeof ShellBoardRoute
  '/company': typeof ShellCompanyRoute
  '/graph': typeof ShellGraphRoute
  '/review': typeof ShellReviewRoute
  '/knowledge/$id': typeof ShellKnowledgeIdRoute
  '/knowledge/': typeof ShellKnowledgeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof ShellActivityRoute
  '/board': typeof ShellBoardRoute
  '/company': typeof ShellCompanyRoute
  '/graph': typeof ShellGraphRoute
  '/review': typeof ShellReviewRoute
  '/knowledge/$id': typeof ShellKnowledgeIdRoute
  '/knowledge': typeof ShellKnowledgeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/activity': typeof ShellActivityRoute
  '/_shell/board': typeof ShellBoardRoute
  '/_shell/company': typeof ShellCompanyRoute
  '/_shell/graph': typeof ShellGraphRoute
  '/_shell/review': typeof ShellReviewRoute
  '/_shell/knowledge/$id': typeof ShellKnowledgeIdRoute
  '/_shell/knowledge/': typeof ShellKnowledgeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/board'
    | '/company'
    | '/graph'
    | '/review'
    | '/knowledge/$id'
    | '/knowledge/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity'
    | '/board'
    | '/company'
    | '/graph'
    | '/review'
    | '/knowledge/$id'
    | '/knowledge'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/activity'
    | '/_shell/board'
    | '/_shell/company'
    | '/_shell/graph'
    | '/_shell/review'
    | '/_shell/knowledge/$id'
    | '/_shell/knowledge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/activity': {
      id: '/_shell/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ShellActivityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/board': {
      id: '/_shell/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof ShellBoardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/company': {
      id: '/_shell/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof ShellCompanyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/graph': {
      id: '/_shell/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof ShellGraphRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/review': {
      id: '/_shell/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ShellReviewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/knowledge/': {
      id: '/_shell/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof ShellKnowledgeIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/knowledge/$id': {
      id: '/_shell/knowledge/$id'
      path: '/knowledge/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof ShellKnowledgeIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellActivityRoute: typeof ShellActivityRoute
  ShellBoardRoute: typeof ShellBoardRoute
  ShellCompanyRoute: typeof ShellCompanyRoute
  ShellGraphRoute: typeof ShellGraphRoute
  ShellReviewRoute: typeof ShellReviewRoute
  ShellKnowledgeIdRoute: typeof ShellKnowledgeIdRoute
  ShellKnowledgeIndexRoute: typeof ShellKnowledgeIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellActivityRoute: ShellActivityRoute,
  ShellBoardRoute: ShellBoardRoute,
  ShellCompanyRoute: ShellCompanyRoute,
  ShellGraphRoute: ShellGraphRoute,
  ShellReviewRoute: ShellReviewRoute,
  ShellKnowledgeIdRoute: ShellKnowledgeIdRoute,
  ShellKnowledgeIndexRoute: ShellKnowledgeIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
